name: 'Validate version labels'
description: 'Checks that a PR has a valid version bump label'
inputs:
  LABELS:
    description: 'The labels from the PR, or provided by the user in a manual run. Only the version bump label is required, but if you choose to provide others, the format is "LABEL1,LABEL2,LABEL3""'
    required: true
outputs:
  VERSION_INSTRUCTION:
    description: "Which of 'patch', 'minor', or 'major' to pass to npm version, or if we should run npm version at all ('none')."
    value: ${{ steps.get-version-instruction.outputs.VERSION_INSTRUCTION }}

runs:
  using: 'composite'
  steps:
    - id: get-version-instruction
      run: |
        shopt -s nocasematch
        LABELS=${{ inputs.LABELS }}

        LABEL=${BASH_REMATCH[1]}
        echo "Version bump label found: $LABEL"
        echo "VERSION_INSTRUCTION=$LABEL" >> $GITHUB_OUTPUT
      shell: bash