name: Setup Git credentials
description: Sets up Git credentials for the action
runs:
  using: "composite"
  steps:
    - name: Check version in package.json
      run: |
        main_package_version=$(git show main:package.json | grep version | head -n 1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')
        current_package_version=$(node -pe "require('./package.json').version")
        if [ "$main_package_version" != "$current_package_version" ]; then
         echo "Error: Package version on current branch ($current_package_version) does not match the one on main branch ($main_package_version)"
        exit 1
        fi
      shell: bash
