name: Changed adapters have the latest EA framework version

on:
  pull_request:
    branches:
      - main

jobs:
  ea-framework-outdated-version:
    name: Changed adapters have the latest EA framework version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: file_changes
        uses: tj-actions/changed-files@v35
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          chmod -R +r .
          changes=${{ steps.file_changes.outputs.all_changed_files }}
          echo "changes"
          echo $changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         

