name: Changed adapters have the latest EA framework version

on:
  pull_request:
    branches:
      - main

jobs:
  ea-framework-outdated-version:
    name: Changed adapters have the latest EA framework version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v32
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs. modified_files }}; do
             echo "$file was modified."
          done
         

