name: Format code with Prettier and open pull request

on:
  push:
    branches:
      - main

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Format code with Prettier
        run: yarn format

      - name: Set up Git credentials
        uses: ./.github/actions/setup-git-credentials

      - name: Create New Branch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              const { data: baseRef } = await github.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/main'
              })
              
              const { data: commit } = await github.git.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: github.context.sha
              })
              
              await github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/heads/new-branch`,
                sha: commit.sha
              })
        

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: app.js
          DESTINATION_BRANCH: new-branch
        run: |
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"

      - name: OPEN PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST /repos/:owner/:repo/pulls \
            --field title="Amazing new feature" \
            --field body="body" \
            --field head="newBranch" \
            --field base="main"    
     
