name: Format code with Prettier and open pull request

on:
  push:
    branches:
      - main

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Set up Git credentials
        uses: ./.github/actions/setup-git-credentials

      - name: Bump version
        run: yarn version --major

      - name: get version
        id: tick-version
        run: |
          PACKAGE_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[", ]//g')  
          echo "VERSION_TAG=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          
        

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: package.json
          DESTINATION_BRANCH: "version-bump/${{ steps.tick-version.outputs.VERSION_TAG }}"
        run: |
          git checkout -b version-bump/${{ steps.tick-version.outputs.VERSION_TAG }}
          gh api -X POST /repos/:owner/:repo/git/refs -f ref="refs/heads/main" -f sha="$GITHUB_SHA" -f "ref=refs/heads/version-bump/${{ steps.tick-version.outputs.VERSION_TAG}}"
          
          git reset HEAD~
          export MESSAGE="${{ steps.tick-version.outputs.VERSION_TAG }}"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          export NEW_COMMIT_SHA=$(gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
          --field encoding="base64" \
          --field branch="$DESTINATION_BRANCH" \
          --field sha="$SHA" | jq -r '.commit.sha')
          
          echo $NEW_COMMIT_SHA
          
          gh api --method POST /repos/:owner/:repo/git/tags \
            --field tag="${{ steps.tick-version.outputs.VERSION_TAG }}" \
            --field message="${{ steps.tick-version.outputs.VERSION_TAG }}" \
            --field object="$NEW_COMMIT_SHA" \
            --field type="commit"

      - name: OPEN PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            response=$(gh api --method POST /repos/:owner/:repo/pulls \
              --field title="Bump version to ${{ steps.tick-version.outputs.VERSION_TAG }}" \
              --field body="This PR was created by the [createVersionBumpPR](./.github/actions/tick-version) GitHub action. It will be merged automatically once checks are successful." \
              --field head="version-bump/${{ steps.tick-version.outputs.VERSION_TAG }}" \
              --field base="${{ github.base_ref || 'main' }}")
            
            pr_url=$(echo $response | jq -r '.html_url')
            pr_number=$(echo $response | jq -r '.number')
            echo "Created pull request: $pr_url (number $pr_number)"
            
            gh api --method PATCH /repos/:owner/:repo/issues/$pr_number \
            --input - << EOF
            { 
              "labels": ["version-bump"]
            }
            EOF