name: Format code with Prettier and open pull request

on:
  push:
    branches:
      - main

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Set up Git credentials
        uses: ./.github/actions/setup-git-credentials

      - name: Bump version
        run: yarn version --major

      - name: get version
        id: tick-version
        run: |
          PACKAGE_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[", ]//g')  
          echo "::set-output name=VERSION_TAG::$PACKAGE_VERSION"
          
        

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: package.json
          DESTINATION_BRANCH: "main"
        run: |
          git checkout -B version-bump/${{ steps.tick_version.outputs.VERSION_TAG }}
          gh api -X POST /repos/:owner/:repo/git/refs -f ref="refs/heads/main" -f sha="$GITHUB_SHA" -f "ref=refs/heads/version-bump/${{ steps.tick_version.outputs.VERSION_TAG}}"
          git reset HEAD~
          export MESSAGE="${{ steps.tick-version.outputs.VERSION_TAG }}"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
          --field encoding="base64" \
          --field branch="$DESTINATION_BRANCH" \
          --field sha="$SHA"   

      - id: create-pr
        name: Create PR
        uses: peter-evans/create-pull-request@v3 # Creates a new branch, adds a commit, and opens a PR
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '${{ steps.tick-version.outputs.VERSION_TAG }}'
          title: 'Bump version to ${{ steps.tick-version.outputs.VERSION_TAG }}'
          body: |
              This PR was created by the [createVersionBumpPR](./.github/actions/tick-version) GitHub action. It will be merged automatically once checks are successful.
          branch: 'version-bump/${{ steps.tick-version.outputs.VERSION_TAG }}'
          delete-branch: true
          labels: version-bump
          base: ${{ github.base_ref || 'main' }}