name: Format code with Prettier and open pull request

on:
  push:
    branches:
      - main

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Set up Git credentials
        uses: ./.github/actions/setup-git-credentials

      - name: Bump version
        run: yarn version --major

      - name: get version
        id: get_version
        run: |
          PACKAGE_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[", ]//g')  
          echo "::set-output name=VERSION_TAG::$PACKAGE_VERSION"

      - name: Create New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -B tempbranch HEAD
          git checkout main
          git reset --hard origin/main
          git checkout -B version-bump/${{ steps.get_version.outputs.VERSION_TAG }} tempbranch
          gh api -X POST /repos/:owner/:repo/git/refs -f ref="refs/heads/main" -f sha="$GITHUB_SHA" -f "ref=refs/heads/version-bump/${{ steps.get_version.outputs.VERSION_TAG }}"
          git push --force-with-lease origin HEAD:refs/heads/${{ steps.get_version.outputs.VERSION_TAG }}

      - name: OPEN PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST /repos/:owner/:repo/pulls \
            --field title="Bump version to ${{ steps.get_version.outputs.VERSION_TAG }}" \
            --field body="PR body" \
            --field head="version-bump/${{ steps.get_version.outputs.VERSION_TAG }}" \
            --field base="main"