name: Format code with Prettier and open pull request

on:
  push:
    branches:
      - test

jobs:
  format-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn

      - name: Format code with Prettier
        run: yarn format


      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: format
          delete-branch: true
          commit-message: "This Commit Automatically formats the code with Prettier"
          committer: "GitHub <noreply@github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          title: "Automatically format code with Prettier"
          body: "This pull request was automatically generated by GitHub Actions."
          base: main
