# This is the entry point for CI. It will setup the application, then run lint, test, and eventually publish if not the main branch
name: 'Main'
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: |
          # Check for outdated ea-framework dependency
          dependency="@chainlink/external-adapter-framework"
          latest_version=0.28.5
          packages=$(find packages -name 'package.json')
          v3_packages=()
          outdated_packages=()
          changes=($(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | xargs -I{} dirname {} | sort -u))
          
          # get the list of v3 EAs
          for file in $(echo $packages); do
            if jq -e ".dependencies[\"$dependency\"]" "$file" >/dev/null; then
              v3_packages+=("$(dirname $file)")
            fi
          done
          
          
          # check if changed code is part of v3 EA
          for changedFile in "${changes[@]}"; do
           for package in "${v3_packages[@]}"; do
              if [[ "$changedFile" == "$package"* ]]; then
                # found change in v3 adapter, comparing versions
                local_version=$(jq -r ".dependencies[\"$dependency\"]" "$package/package.json")
                if [ "$local_version" != $(echo $latest_version) ]; then
                  outdated_packages+=("$package")
                fi
              fi
           done
          done
          
          if [ ${#outdated_packages[@]} -gt 0 ]; then
            echo "The following packages have an outdated \"$dependency\" dependency:"
            for file in "${outdated_packages[@]}"; do
              echo "- $file"
            done
          exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
