# This is the entry point for CI. It will setup the application, then run lint, test, and eventually publish if not the main branch
name: 'Main'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            ./**/coverage/tmp/*.json
            ./**/coverage/coverage-summary.json
  # Only run if tests have run and completed successfully
  code-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - uses: actions/download-artifact@v3
        with:
          name: coverage-reports
      - run: |
          # save coverage for statements in a branch name ('coverage-pr-NUMBER') so it can extracted in a different workflow
          COVERAGE_STATEMENTS=$(cat coverage/coverage-summary.json | jq '.total.statements.pct | round')
          BRANCH="coverage-pr-$COVERAGE_STATEMENTS"
          gh api -X POST /repos/:owner/:repo/git/refs -f ref="refs/heads/main" -f sha="$GITHUB_SHA" -f "ref=refs/heads/$BRANCH"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn code-coverage