# This is the entry point for CI. It will setup the application, then run lint, test, and eventually publish if not the main branch
name: 'Main'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          current_package_version=$(node -pe "require('${{ github.workspace }}/package.json').version")
          echo $current_package_version
          git fetch origin ${{ github.event.repository.default_branch }}
          git checkout ${{ github.event.repository.default_branch }}
          git branch
          main_package_version=$(node -pe "require('${{ github.workspace }}/package.json').version")
          echo $main_package_version
          
          if [ "$main_package_version" != "$current_package_version" ]; then
          echo "Error: Package version on current branch ($current_package_version) does not match the one on ${{github.event.repository.default_branch}} branch ($main_package_version)"
          exit 1
          fi
            
        
