# This is the entry point for CI. It will setup the application, then run lint, test, and eventually publish if not the main branch
name: 'Main'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            ./**/coverage/tmp/*.json
            ./**/coverage/coverage-summary.json
  # Only run if tests have run and completed successfully
  code-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set-git-credentials
      - run: yarn install
      - uses: actions/download-artifact@v3
        with:
          name: coverage-reports
      - run: |
          # save coverage summary in a branch 'coverage-pr-PR_NUMBER' so we can have access to it in a different workflow
          BRANCH="coverage-pr-${github.event.pull_request.number}"
          git checkout -b $BRANCH
          gh api -X POST /repos/:owner/:repo/git/refs -f ref="refs/heads/main" -f sha="$GITHUB_SHA" -f "ref=refs/heads/$BRANCH"
          
          git add coverage/coverage-summary.json
          git commit -m "add coverage"
          git push --force
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn code-coverage